money_list/urls.py
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'money_list'

urlpatterns = [
    url(r'^$', views.money_list.as_view(), name='money_list'),
    url(r'^insert/$', views.check_post, name='money_list_insert'),
]
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

money_main/urls.py
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'money_main'

urlpatterns = [
    url(r'^$', views.money_main.as_view(), name='money_main'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

money_manage/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('money_main.urls')),
    path('index/', include('money_main.urls')),
    path('home/', include('money_main.urls')),

    #transaction app
    path('list/', include('money_list.urls')),
]

money_list/models.py
from django.db import models

# Create your models here.

class MoneyTransaction(models.Model):
    num = models.AutoField(primary_key=True)
    user_num = models.ForeignKey('User', models.DO_NOTHING, db_column='user_num')
    entry_name = models.CharField(max_length=50, blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def money_save(self):
        self.save()

    class Meta:
        managed = False
        db_table = 'money_transaction'


class User(models.Model):
    num = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=20)
    pwd = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user'

money_main/models.py
from django.db import models

# Create your models here.

money_list/forms.py
from django import forms
from .models import MoneyTransaction

class MoneyForm(forms.ModelForm):
    class Meta:
        model = MoneyTransaction
        fields = ('entry_name', 'price', 'description')

money_list/views.py
from django.shortcuts import render, redirect
from .models import MoneyTransaction
from .forms import MoneyForm

from django.views import View
from django.views import generic

# Create your views here.

class money_list(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        template_name = 'money_list/list.html'
        money_transaction = MoneyTransaction.objects.all()
        return render(request, template_name, {"money_transaction": money_transaction})

def check_post(request):
    template_name = 'money_list/money_list_success.html'
    if request.method == "POST":
        form = MoneyForm(request.POST)
        if form.is_valid():
            money = form.save(commit=False)
            money.money_save()
            message = "목록을 추가하였습니다."
            return render(request, template_name, {"message": message})
    else:
        template_name = 'money_list/money_list_insert.html'
        form = MoneyForm
        return render(request, template_name, {"form" : form})

money_main/views.py
from django.shortcuts import render, redirect

from django.views import View
from django.views import generic

# Create your views here.

class money_main(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        template_name = 'money_main/index.html'
        return render(request, template_name)

money_list/templates/money_list/list.html
<html>
    <head>
        Money Transaction List
    </head>

    <body>
        <div class="col-md-12">
            <div class="container">
                {% for list in money_transaction %}
                    <div class="list-group-item"><input type="checkbox" name={{list.entry_name}} value={{list.entry_name}}>{{list.entry_name}} : {{list.price}}</div>
                {% endfor %}
            </div>
        </div>

    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'money_list:money_list_insert' %} '">
        목록 추가
    </button>
    </body>
</html>

money_list/templates/money_list/money_list_insert.html
<!-- Model Body -->
<html>
    <form method="POST" class="post-form" action="%url 'money_list:money_list_insert' %}">
        {%csrf_token%}

        {{form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>
</html>

money_list/templates/money_list/money_list_success.html
<script>
    message = "{{ message }}";
    consol.log(message);
    alert(message);
    window.location.href = "{% url 'money_list:list' %}"
</script>

money_main/templates/money_main/index.html
money main